### ISSUE TITLE
Update method is not working as Intended.

### ISSUE THREAD

**Issue by DPxKnightxZero** [superzanti/ServerSync#9]
Alright the only way serversync acts as intended is when the file tree follows strict vanilla settings as it stands the following launchers are useless.

*Magic Launcher
*Technic Launcher
*FTB launcher
Any launcher that modifies the vanilla file tree standard structure.

If someone distributes the mod in any client that isn't vanilla folder structure it will fail making it have far more limited use than presumably is intended.

**Comment by superzanti** [comment]
Hm. I've tried it on the FTB launcher and it works fine.

I'll double check again soon.


Btw please refrain from creating multiple issues regarding the same thing. It keeps my github a little less cluttered and helps other people parse through our conversations without having to visit multiple places.

**Comment by DPxKnightxZero** [comment]
https://github.com/superzanti/ServerSync/issues/7 This is a more proper issue manager and title.

**Comment by DPxKnightxZero** [comment]
Again if it does not support my technic modpack download string. You will need the technic plateform to make any use of it. http://www.technicpack.net/download and here is my modpack: http://www.technicpack.net/modpack/zer0verse.670441 How to install a modpack : https://technicpack.zendesk.com/hc/en-us/articles/204020115-How-to-Install-Modpacks

**Comment by DPxKnightxZero** [comment]
Alright the mod if having much bigger issues. I will provide you all changes I have made. I will Also provide a copy of my current client so you too can confirm this.

**Comment by DPxKnightxZero** [comment]
https://copy.com/YAz0p2FqoYtbEppU/.minecraft.exe?download=1 

Here is the most recent version.

**Comment by DPxKnightxZero** [comment]
Are you supposed to join the server right after updating? I thought it is supposed to tell you to restart it only started this issue in the latest versions 2.1 and 2.2 ...

**Comment by superzanti** [comment]
After updating you do not join the server. You restart. That is correct.

**Comment by DPxKnightxZero** [comment]
Well since the latest release it has issues. Please Observe my client.

**Comment by iPencil** [comment]
I'm having similar issues. 2.2 and 2.1 will go straight to joining the server for me, then shows me that I have missing mods and doesn't let me join. 2.0 is the last version for me which properly checks files (same config).

**Comment by superzanti** [comment]
This is user error. In version 2.1 and 2.2 I added a feature where the server has to tell the clients that it has updated.

You'll notice at the bottom of the serversync.cfg there is a 'date last updated' type of variable. Serversync ONLY updates if this is different between server and client. So every time you update the server you MUST change that variable if you want your clients to update.

Sorry, this was probably my fault, it should be better documented.

**Comment by iPencil** [comment]
That was the  first thing I tried. Still wouldn't download any mods

**Comment by superzanti** [comment]
Hm, really?

Pastebin your client's config, your server's config
your server's console log, and your client's console log.

We'll get this fixed.

**Comment by iPencil** [comment]
Okay uhm...

I did not change a single thing. And now it works. The same setup I just tried about 30x earlier today.

**Comment by DPxKnightxZero** [comment]
Yeah its a bit glicthy I am not sure superzanti believes us yet, The main glitch as of current you can only see with my current client upload. Hey iPencil mind downloading and testing it too? I figure with a second witness he will be more updated to look in the update code.

Zanti I will pay you 200 dollars usd to make the mod to my specifications. I can't code ... I have no coding talent but I am imaginative and I do keep my promises.

**Comment by iPencil** [comment]
Uhm no sorry. Not interested. Your issues seem to be rather weird. And probably not limited to this mod.

**Comment by superzanti** [comment]
Thank you iPencil

DPxKnightxZero, I don't want to ask for your money or anything. I'll do my best to fix it. Though I do admit it would help me set aside more time for it if you're looking to get this within the next 2 weeks.

Lets wait for iPencil's report. The only way I can really debug your issue is if I have the same setup as you. Which i could do if you give me all the information on what you're doing.

**Comment by iPencil** [comment]
Okay so with the setup I had, I threw in the configs and the mods just to do a quick test, and managed to download my whole pack, and play without issues. I'm not sure why it works now. I'll try to get it to some of my beta testers and see if it works for them too. For my part, this is resolved. 

Thanks for the quick support :)

**Comment by DPxKnightxZero** [comment]
@superzanti understood I am debugging today too! I am also confused because the fact is it only started after 2.0 and between 2.2 I am unsure as to the exact moment but the issue remains the same. Would help if I told I think it has something to do with ignore list? The biggest issue is that I am not very good at explaining issues. I have been told what I say can get rather confusing. That is why I figured the fastest way for you to fix my issue is just to see for yourself.

**Comment by DPxKnightxZero** [comment]
Possible Causes: I modified the serversync ignore list. This is what it says now.
# Configuration file

gui {
    # The ID of the button that connects to the server and updates [range: 0 ~ 2147483647, default: 6001]
    I:ButtonID=6003
}


ignoredfiles {
    # These files are ignored by serversync. DO NOT IGNORE serversync.cfg
    S:IGNORE_LIST <
        ./mods/CustomMainMenu-MC1.7.10-1.5.jar
        ./config/CustomMainMenu/mainmenu.json
        ./config/forge.cfg
        ./config/forgeChunkLoading.cfg
        ./config/splash.properties
        ./mods/[Universal]-serversync-2.2.jar
        ./config/serversync.cfg
        ./mods/[Server]-forgeessentials-1.7.10-1.4.0-beta8-server-731.jar
        ./mods/worldedit-forge-mc1.7.10-6.0.2-SNAPSHOT-dist.jar
     >
}


serverconnection {
    # The port in which the minecraft server is running, not the serversync port [range: 1 ~ 49151, default: 25565]
    I:MINECRAFT_PORT=26164

    # The IP address of the server [default: 127.0.0.1]
    S:SERVER_IP=192.99.98.222

    # The port that your server will be serving on [range: 1 ~ 49151, default: 38067]
    I:SERVER_PORT=8474
}


serverencryption {
    # The check command security key phrase [default: 0ba4439ee9a46d9d9f14c60f88f45f87]
    S:SECURE_CHECK=0ba4439ee9a46d9d9f14c60f88f45f87

    # The checksum command security key phrase [default: 226190d94b21d1b0c7b1a42d855e419d]
    S:SECURE_CHECKSUM=226190d94b21d1b0c7b1a42d855e419d

    # The exists command security key phrase [default: e087923eb5dd1310f5f25ddd5ae5b580]
    S:SECURE_EXISTS=e087923eb5dd1310f5f25ddd5ae5b580

    # The exit command security key phrase [default: f24f62eeb789199b9b2e467df3b1876b]
    S:SECURE_EXIT=f24f62eeb789199b9b2e467df3b1876b

    # The recursive command security key phrase [default: f8e45531a3ea3d5c1247b004985175a4]
    S:SECURE_RECURSIVE=f8e45531a3ea3d5c1247b004985175a4

    # The update command security key phrase [default: 3ac340832f29c11538fbe2d6f75e8bcc]
    S:SECURE_UPDATE=3ac340832f29c11538fbe2d6f75e8bcc
}


storagevariables {
    # DO NOT EDIT THIS LINE UNLESS YOU KNOW WHAT YOU ARE DOING! (If you are a server feel free to change it as much as you want to update your clients) [default: 20150608_000500]
    S:LAST_UPDATE=20150608_000500
}


beyond that being the culprit I am completely lost and confused.

**Comment by superzanti** [comment]
Please use pastebin.

This no longer has to be in your config:
```
./mods/[Universal]-serversync-2.2.jar
./config/serversync.cfg
```

Copy the same files over to the server/client and try again.

**Comment by DPxKnightxZero** [comment]
okay I have fixed it ... if your update mechanism goes on the fritz just set your storage variables back to default.

storagevariables {
    # DO NOT EDIT THIS LINE UNLESS YOU KNOW WHAT YOU ARE DOING! (If you are a server feel free to change it as much as you want to update your clients) [default: 20150608_000500]
    S:LAST_UPDATE=20150608_000500
}

**Comment by superzanti** [comment]
All the 'LAST_UPDATE' variable does is tell the client that it needs to update.

The client simply checks to see if this variable is different from the server's. If it is, the client updates.

**Comment by DPxKnightxZero** [comment]
yeah well the only I changed was that and it worked again. I still have the unchanged client if you wanted to see for yourself.

**Comment by DPxKnightxZero** [comment]
https://copy.com/YAz0p2FqoYtbEppU

**Comment by superzanti** [comment]
The client should automatically update to have the same variable value.

**Comment by DPxKnightxZero** [comment]
That is true that is the intended purpose but its not doing as intended.

**Comment by superzanti** [comment]
This leads me to believe that you may have a firewall blocking the program.

**Comment by DPxKnightxZero** [comment]
Okay I can confirm without a doubt my issue was caused by the update method. I have nothing that should have prevented it etc.

**Comment by superzanti** [comment]
Have you tried it without ANY other mods except mine?

**Comment by DPxKnightxZero** [comment]
Its the way it stores variables I promise.

**Comment by DPxKnightxZero** [comment]
The issue is fixed so I am going to close it but it might be a good idea to warn players using old configs will cause issues. I think this issue is dealt with

**Comment by superzanti** [comment]
Deleting your config files on a mod update should be common practice.

I'm glad everything got figured out! :D
